=head1 Do not base your design on junctions and autothreading

=head2 Example

TODO

=head2 Rationale

Junctions and the associated autothreading fascinate newcomers. Sometimes
they want to base an entire system design on junctions (for example solving
equations or systems related to declarative programming).

Since junctions are not meant to represent sets, this is usually a bad idea;
debugging code with junctions is hard, and often confusing to read.

So the author recommmends to use junctions only locally, as in
C<if $x eq 'a' | 'z' { ... }>, or for matchers such as arguments to C<grep>,
C<first> or C<when>.

=head2 Exceptions

None known yet; Note that this rule does not mean "do not use junctions"; see
previous section.

=head2 Champion

moritz
